### PR TITLE
Merge upstream changes

### LINKED ISSUE #22: You should pull from origin
To get the OSX media next and media prev keys working
https://github.com/tmk/tmk_keyboard/pull/199

### PR DESCRIPTION
**Pull request by marknsikora**
Merge changes from upstream and patch makefiles to work with new core library location. Fixes #22.

### CODE REVIEW

**Comment by notmatt** [comment]
Merged this diff & tested on my own fork, it's working well for me so far -- thanks @marknsikora

**Comment by cub-uanic** [comment]
@marknsikora please note that most fresh code in my repo is on cub_layout branch, NOT on master.

**Comment by squarefrog** [comment]
What needs to happen to push this forward? I'm willing to help out if I can, as it's getting hard to keep my fork updated with upstream. I think getting https://github.com/cub-uanic/tmk_keyboard/ in sync with https://github.com/tmk/tmk_keyboard/ would be very beneficial.

Hopefully this could be merged into the main repository, which would reduce the burden on @cub-uanic.

**Comment by marknsikora** [comment]
After I got access to the repo I updated my branch to track the newer upstream and wanted to test that the new changes had no negative side effect. I've been using this version as my daily driver for a few weeks now without issue.

**Pull request merged**
