### PR TITLE
Dvorak Layout

### PR DESCRIPTION
**Pull request by Xyverz**
Here's the pull request with my Dvorak layout. I've made it a bit more generic. I wasn't sure if you wanted this submitted to the keymap_dvorak.h file, so I committed it as keymap_xyverz.h.

### CODE REVIEW

**Comment by marknsikora** [comment]
The existing dvorak layout is empty, feel free to put your layout there. Yours doesn't seem to contain too much personal stuff so will be a good base layout for dvorak users.

**Comment by Xyverz** [comment]
Okay, I'll add this to the dvorak file and make another pull request.

**Comment by squarefrog** [comment]
No - while you have this Pull Request open, and changes you push will be reflected here. Thanks for submitting this @Xyverz !

**Comment by Xyverz** [comment]
I've updated the keymap_dvorak.h with the contents of the keymap_zrevyx.h file. I'd like to merge it into this request, but unfortunately, I'm not sure how to do that using the web interface.

**Comment by Xyverz** [comment]
Ignore my last comment. I see that the updated keymap_dvorak.h file is there.

**Comment by squarefrog** [comment]
Sorry for not getting back to you @Xyverz - thanks for submitting this, I've merged it in now.

**Comment by marknsikora** [comment]
This merge won't work. It's still using the old layout scheme.

**Comment by squarefrog** [comment]
Fixed in cbf4e5b6ff774d53013a3c2d10852858600a8d7e 👍

**Comment by Xyverz** [comment]
Thanks for fixing that. Much appreciated.

**Pull request merged**
